### ISSUE TITLE
Couldn't find Pistachio '9321535_add_year.csv file

### ISSUE THREAD

**Issue by Pranav2907** [xiaodanyin/Egret#1]
I am trying to reproduce the results of the paper but as mention pistachio dataset was used for pre-training of the model but I couldn't find the particular file and also the referenced paper leads no where. Could you please help?

**Comment by xiaodanyin** [comment]
The Pistachio dataset is a commercial dataset offered by Nextmove. To access it, please review the information at this link (https://www.nextmovesoftware.com/pistachio.html) and subscribe using the specified method.
